import type { ToolItem } from '@/components/ToolGroup.vue'
import { t, type MessageKey } from '@/i18n'

// Rule-based follow-up questions: the last tool of the reply picks a topic, the topic picks 3–4 fixed
// questions. Questions that need a robot use the last robot_sn seen in the reply; without one, the
// generic set is used. Nothing here is generated by the model.
type Topic = 'status' | 'reports' | 'maps' | 'command' | 'fleet'
const TOPIC_BY_TOOL: Record<string, Topic> = {
  get_robot_status: 'status', describe_work_state: 'status', get_robot_capabilities: 'status',
  list_task_reports: 'reports', get_task_report_map_images: 'reports',
  list_robot_maps: 'maps', get_map_canvas: 'maps', list_map_resources: 'maps', list_task_resources: 'maps', list_charging_positions: 'maps',
  get_command_status: 'command', wait_for_command: 'command', list_command_history: 'command',
  start_task: 'command', pause_task: 'command', resume_task: 'command', stop_task: 'command', navigate_home: 'command',
  list_robots: 'fleet',
}
const QUESTIONS: Record<Topic, MessageKey[]> = {
  status: ['follow.reports', 'follow.map', 'follow.tasks'],
  reports: ['follow.status', 'follow.reportMap', 'follow.efficiency'],
  maps: ['follow.status', 'follow.reports', 'follow.resources'],
  command: ['follow.status', 'follow.commandHistory', 'follow.reports'],
  fleet: ['follow.fleetOffline', 'follow.fleetLowBattery', 'follow.fleetWorking'],
}
const GENERIC: MessageKey[] = ['follow.fleetOffline', 'follow.fleetLowBattery', 'follow.fleetWorking']

export function followUps(tools: ToolItem[]): string[] {
  const last = tools[tools.length - 1]
  if (!last) return []
  const topic = TOPIC_BY_TOOL[last.name] ?? 'fleet'
  const sn = [...tools].reverse().map(tool => (tool.input as { robot_sn?: unknown; robot_sn_list?: unknown })).map(input =>
    typeof input?.robot_sn === 'string' ? input.robot_sn : Array.isArray(input?.robot_sn_list) && input.robot_sn_list.length === 1 ? String(input.robot_sn_list[0]) : '',
  ).find(Boolean)
  const keys = topic !== 'fleet' && !sn ? GENERIC : QUESTIONS[topic]
  return keys.map(key => t(key, { sn: sn ?? '' }))
}

/** Suggested first questions on the empty chat. */
export const STARTERS: { key: MessageKey; icon: 'alert' | 'chart' | 'battery' | 'map' }[] = [
  { key: 'starter.offline', icon: 'alert' },
  { key: 'starter.reports', icon: 'chart' },
  { key: 'starter.battery', icon: 'battery' },
  { key: 'starter.maps', icon: 'map' },
]
